version: "3.9"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - mongo

    mongo:
        image: mongo:7.0.3-jammy
        command: mongod           
        ports:
            - "27017:27017"
        restart: always
